### ISSUE TITLE
Something wrong with numbered list in Exercise 1.6

### ISSUE THREAD

**Issue by jasoncpatton** [opensciencegrid/virtual-school-pilot-2020#20]
https://github.com/opensciencegrid/virtual-school-pilot-2020/blob/master/docs/materials/htc/part1-ex6-remove.md#removing-all-of-your-jobs

The numbered list does not render correctly with the OSG special sauce applied, see: https://opensciencegrid.org/virtual-school-pilot-2020/#materials/htc/part1-ex6-remove/#removing-all-of-your-jobs

**Comment by osg-cat** [comment]
Easy fix — just remember that there needs to be a blank line above and below a list.
