### ISSUE TITLE
Intro to HTC Exercise 2.3 and 2.4 were flipped without editing intro sections

### ISSUE THREAD

**Issue by jasoncpatton** [opensciencegrid/virtual-school-pilot-2020#23]
Exercise 2.3 talks about having done `queue ... matching` in the previous exercise, which is now Bonus Exercise 2.4. There are a few other parts of the exercise that reference the once-previous exercise (see Extra Challenge 1, for example).

**Comment by jasoncpatton** [comment]
@lmichael107 I can't assign users to issues, but I think you might be best to handle it knowing why you chose to flip these and make `queue ... from` the focus.

**Comment by lmichael107** [comment]
@iross is handling it! (we discussed earlier today)

**Comment by osg-cat** [comment]
I think that I just (Sunday, 2 p.m.) merged in the relevant changes. @iross or @jasoncpatton, please check that the exercises make sense in their new order now.

**Comment by iross** [comment]
Confirmed, changes are there and look ok to me, but they could use another set of eyes (@jasoncpatton or @JoshKarpel were slated to test) .

**Comment by JoshKarpel** [comment]
I'm doing a pass this morning and will take a close look at them.

**Comment by JoshKarpel** [comment]
LGTM :+1:

**Comment by lmichael107** [comment]
Great. Thanks, everyone! Do we need to assign and/or resolve this issue?
